config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'
  get 'sessions/destroy'
  resources :users
  resources :friendships

  get '/auth/twitter'
  get '/auth/twitter/callback', to: 'sessions#create'
  get '/login', to: 'users#index'
  get '/logout', to: 'sessions#destroy'

  root 'users#index'

  get '/friends', to: "users#friends"

  post '/friendships', to: "friendships#update"

  get '/about', to: "users#about"

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  after_validation :geocode,
    if: lambda{|obj| obj.location_changed?}
  geocoded_by :location

  has_many :friendships
  has_many :users, through: :friendships
  has_many :texts, foreign_key: :f_id
  has_many :us, through: :texts

  def knows(user)
    self.friendships.find_by(user_id: user.id)
  end

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend
end

app/models/text.rb
class Text < ActiveRecord::Base

  belongs_to :u, class_name: 'User'
  belongs_to :f, class_name: 'Friend'

end

app/models/user.rb
class User < ActiveRecord::Base
  after_validation :geocode
  geocoded_by :ip_address,
    latitude: :lat, longitude: :lon
  
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :texts, foreign_key: :u_id
  has_many :fs, through: :texts

  accepts_nested_attributes_for :friendships
  
  def self.create_with_omniauth(auth_hash)
    self.create(
      provider: auth_hash[:provider],
      uid: auth_hash[:uid],
      name: auth_hash[:info][:name]
    )
  end

  # Ben's number : "+15038942566"
  # Ilana's number : "+14125088025"
  # Emily's number : "+18456416152"

  def notify(to, friend, location)
    account_sid = ENV['TWILIO_ACCOUNT_SID']
    auth_token = ENV['TWILIO_AUTH_TOKEN']
    @client = Twilio::REST::Client.new account_sid, auth_token
    message = @client.account.messages.create(
      :body => "Your friend #{friend} just checked in at #{location}! (via Who'sAround)",
      :to => "#{to}",
      :from => "+14129064747"
    )
  end

  def find_friends_within_range
    lat = self.lat
    lng = self.lon
    friends_in_range = Friend.near([lat, lng], 10).select do |friend|
      friend if friend.friendships.detect {|f| f.user_id == self.id && f.stalking == true && !texts_contain_status(friend)}
    end
  end

  def send_text_updates
    if self.phone != nil || self.phone != ""
      find_friends_within_range.each do |f|
        self.notify(self.phone, f.name, f.location)
      end
    end
  end

  def texts_contain_status(f)
    if self.texts.find_by(u_phone: self.phone, f_update: f.updated_at)
      return true
    else
      self.texts.create(u_id: self.id, u_phone: self.phone, f_id: f.id, f_update: f.updated_at)
      return false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authentication_required

  private
    def authentication_required
      redirect_to login_path if !logged_in?
    end

    def logged_in?
      !!current_user
    end
    helper_method :logged_in?

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  # before_action :set_user, only: [:show, :edit]
  # skip_before_action :authentication_required, :only => [:index]

  def update
    @friendship = Friendship.find(params[:id])
    @user = User.find(@friendship.user_id)
    if @friendship.update_attribute('stalking', params[ :stalking])
      flash.now[:notice] = "You have successfully updated your friend."
    else
      flash.now[:error] = "Could not save changes."
    end
    redirect_to @user
  end

  def create
  end


  def new
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authentication_required

  def new
  end

  def create
    reset_session
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = auth_hash['extra']['access_token'].consumer.key
      config.consumer_secret     = auth_hash['extra']['access_token'].consumer.secret
      config.access_token        = auth_hash['credentials']['token']
      config.access_token_secret = auth_hash['credentials']['secret']
    end

    @user = User.find_by_provider_and_uid(auth_hash[:provider], auth_hash[:uid]) || User.create_with_omniauth(auth_hash)
    @user.ip_address = '74.2.111.146'  # HARDCODED IP FOR DEVELOPMENT
    # @user.ip_address = request.location.data['ip']
    @user.save
    @user.location = Geocoder.search("#{@user.lat}, #{@user.lon}").first.data['formatted_address']
    @user.save
    session[:user_id] = @user.id
    session[:current_user] = @user

    old_friendships = @user.friendships
    new_friendships = []
    client.friends.attrs[:users].each do |friend|
      f = Friend.find_by(twitter_id: friend[:id])
      unless f
        f = Friend.new
        f.twitter_id = friend[:id]
        f.save
      end
      unless f.knows(@user)
        f.friendships.build(user_id: @user.id)
      end
      f.name = friend[:name]
      f.pic = friend[:profile_image_url].to_s.gsub("_normal", "")
      if friend[:status][:geo?]
        f.location = Geocoder.search(friend[:status][:geo][:coordinates].join(',')).first.data['formatted_address']
        f.latitude = friend[:status][:geo][:coordinates].first
        f.longitude = friend[:status][:geo][:coordinates].last
      else
        f.location = friend[:location]
      end
      f.save
      new_friendships << f.friendships.find_by(user_id: @user.id)
    end

    @user.friendships.each do |friendship|
      friendship.destroy if !new_friendships.include?(friendship)
      friend = old_friendships.find_by(friend_id: friendship.friend_id)
      friendship.stalking = friend.stalking if friend
    end
    render 'users/show'
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  protected
    def auth_hash
      env['omniauth.auth']
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit]
  skip_before_action :authentication_required, :only => [:index, :about]

  def update
    @user = User.find(params[:id])
    if @user.update(update_user_loc_and_phone)
      redirect_to(@user)
    else
      render :edit
    end
  end

  def show
  end

  def edit
  end

  def create
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def update_user_loc_and_phone
    params.require(:user).permit([:location, :phone])
  end
     
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_nav.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Who's Around?", root_url, :class => "navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to 'Home', root_url %></li>
            <% if logged_in? %>
              <li><%= link_to 'Profile', edit_user_path(session[:user_id]) %></li>
              <li><%= link_to 'Friends', user_path(session[:user_id]) %></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "About", "/about" %></li>
                <li><%= link_to current_user.name, user_path(current_user) %></li>
                <li><%= link_to "Log Out", logout_path %></li>
            <% else %>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "About", "/about" %></li>
                <li><%= link_to "Log in with Twitter", "auth/twitter" %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Who's Around?</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Slab|Montserrat' rel='stylesheet' type='text/css'>
     <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
   

</head>
<body>

<%= render "layouts/nav" %>

<div class="container content">
<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
<%= yield %>
</div>


<div class="footer">
Built with &#9825; at the <a href="http://www.flatironschool.com" target="_blank">Flatiron School</a>
<span style="float:left;padding-left:2px;">  &#169; Copyright 2014 MIT License</span>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

</body>
</html>

app/views/users/about.html.erb
<br>
<br>
<br>
<br>
<div align="center">  
  <h2>Who's Around? was made by <%= link_to "Emily Lowing", "https://twitter.com/elowing" %>, <%= link_to "Ilana Sufrin", "https://twitter.com/ilanasufrin" %> and <%= link_to "Ben Serviss", "https://twitter.com/benserviss" %> at <%= link_to "The Flatiron School", "http://www.flatironschool.com  " %>.
  </h2>
<br>
<br>
<br>
<br>
Logo 'Friends' designed by Rob Schill from the Noun Project<br>
Arrow designed by Thomas Le Bas from the Noun Project
</div>

app/views/users/edit.html.erb
<div style="height:100px"><!-- This is literally just to take up styling space --></div>

<div class="users-edit-page-content">

<h2>Edit Your Location</h2>


<%= form_for(@user) do |u|%>
<%= u.hidden_field :user_id, :value => @user.id %>
<%= u.text_area :location, :cols => "50", :rows => "3", :placeholder => "Enter Full Address" %>
<br>
<% if @user.phone == nil %>
  <h2>Add Your Phone Number</h2>
  <%= u.telephone_field :phone, :placeholder => "Phone number" %>
<% else  %>
  <h3>Update Your Phone Number</h3>
  <%= u.telephone_field :phone, :placeholder => @user.phone %>
<% end %>
  <%= u.submit "Save" %>
<% end %>

</div> <!-- users-edit-page-content -->

app/views/users/index.html.erb
<div class="users-index-page-content">
<br><br>
<div align="center">
  <%= link_to image_tag('/assets/logo.png', size: '200', class: "logo-image"),users_path %><br>
  <h1>Who's Around?</h1><br>
  <h3>Find your friends nearby!</h3>
</div>

</div> <!-- users-index-page-content -->

<%#= link_to image_tag(clothing_article.photo.url), user_clothing_article_path(clothing_article.user_id, clothing_article.id)%>

app/views/users/show.html.erb
<div class="users-show-page-content">

<div class="jumbotron">
  <h3>My location: <%= @user.location ? @user.location : link_to("Set my location", edit_user_path(@user)) %></h3>
  <h3>My phone number: <%= @user.phone ? @user.phone : link_to("Set my phone number", edit_user_path(@user)) %></h3>
</div> <!-- jumbotron -->

<h2 class="my-friends-heading">
  <!-- <a href="javascript:void(0);" class="slide-left"> -->
    <%= image_tag('/assets/arrow_g.png', size: '45', :id => "slide-left") %> 
  <!-- </a> -->
   My Friends 
  <!-- <a href="javascript:void(0);" class="slide-right"> -->
    <%= image_tag('/assets/arrow_g.png', size: '45', :class => 'flip-horizontal', :id => "slide-right") %>
  <!-- </a> -->
  <br>
</h2>

<div class="friends-container">

<% @user.friends.each do |friend| %><br>
  <% friendship = Friendship.find_by(friend_id: friend.id) %>
  <div class="panel panel-info col-md-4" style="margin:5px;border-radius:15px">
    <div class="panel-heading">
      <h3 class="panel-title label"><%= label_tag friend.name %></h3>
    </div> <!-- panel-heading -->
    <div class="panel-body"> 
      <img src="<%= friend.pic %>"style="height:200px;width:auto"><br>
      <h4> <%= friend.location if friend.location %><br> </h4>
      
      <%= form_tag("/friendships/#{friendship.id}", method: :patch, remote: true) do %>
        <% if friendship.stalking%>
          <%= label_tag 'stalking', 'Currently Following', class: 'stalking_check' %>
        <% else %>
          <%= label_tag 'stalking', 'Follow this Friend', class: 'stalking_check' %>
        <% end %>
        <%= check_box_tag 'stalking', true, friendship.stalking, class: 'stalking' %><br>
        <%= submit_tag 'Update Friend', hidden: true %>
      <% end %>
    </div> <!-- panel-body -->
  </div> <!-- panel-info -->
<% end %>
</div> <!-- friends-container -->

</div> <!-- users-show-page-content -->